# GITHUB: https://github.com/garethcmatthews/docker-lamp
version: "3.8"
networks:
    frontend:
        driver: bridge
        internal: false
    backend:
        driver: bridge
        internal: true
services:
    php:
        # DOCKER HUB: https://hub.docker.com/_/php/
        build: ./resources/docker/development/php-8.1.27/apache-php
        container_name: lamp-php
        depends_on:
            mysql:
                condition: service_healthy
        env_file:
            - 'docker.env'
        networks:
            - backend
            - frontend
        ports:
            - 8080:80
        volumes:
            - ./:/var/www/html
            - /var/www/html/vendor
    mysql:
        # DOCKER HUB: https://hub.docker.com/_/mysql/
        build: ./resources/docker/development/php-8.1.27/mysql
        container_name: lamp-mysql
        env_file:
            - 'docker.env'        
        healthcheck:
            test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
            timeout: 30s
            interval: 10s
            retries: 10
        command: --default-authentication-plugin=mysql_native_password
        networks:
            - backend
        ports:
            - 3306:3306
    phpmyadmin:
        # DOCKER HUB: https://hub.docker.com/_/phpmyadmin
        container_name: lamp-phpmyadmin
        depends_on:
            mysql:
                condition: service_healthy
        env_file:
            - 'docker.env'        
        image: phpmyadmin:5.2.1-apache
        networks:
            - backend
            - frontend
        ports:
            - 8888:80
