# GITHUB: https://github.com/garethcmatthews/docker-lamp
version: "3.8"
networks:
    frontend:
      driver: bridge
      internal: false
    backend:
      driver: bridge
      internal: true
services:
  php:
    # DOCKER HUB: https://hub.docker.com/_/php/
    build: ./resources/docker/development/php-7.4/apache-php
    container_name: php
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - backend
      - frontend
    ports:
      - 8080:80
    restart: always
    volumes:
      - ./:/var/www/lamp
      - /var/www/lamp/vendor/
  mysql:
    # DOCKER HUB: https://hub.docker.com/_/mysql/
    command: --default-authentication-plugin=mysql_native_password        
    container_name: mysql        
    environment:
      - MYSQL_DATABASE=lamp
      - MYSQL_USER=dev
      - MYSQL_PASSWORD=iamdev
      - MYSQL_ROOT_PASSWORD=iamroot
    healthcheck:
        test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
        timeout: 30s
        interval: 10s
        retries: 10            
    image: mysql:8.3.0          
    networks:
        - backend
    ports:
        - 3306:3306
    restart: always
  phpmyadmin:
    # DOCKER HUB: https://hub.docker.com/_/phpmyadmin
    container_name: phpmyadmin
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      - PMA_HOST=mysql
      - PMA_PORT=3306
      - PMA_USER=root
      - PMA_PASSWORD=iamroot
    image: phpmyadmin:5.2.1
    networks:
      - backend
      - frontend
    ports:
      - 8888:80
    restart: always
